// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pchxmtkhqgjlevvzgqoi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBjaHhtdGtocWdqbGV2dnpncW9pIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzA4MzQ5MDgsImV4cCI6MjA4NjQxMDkwOH0.y1fq9t747FZIApHgDpE9PNHZLQTVDuPi4ICBnpPXv9M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});